language: node_js
node_js: stable

deploy:
  provider: pages
  skip-cleanup: false
  github-token: $GITHUB_TOKEN
  local-dir: build
  target-branch: gh-pages
  keep-history: false
  verbose: true
  on:
    branch: publish

script:
  - npm run build

cache:
  directories:
    - node_modules
  
branches:
  only:
    - publish
