language: node_js
node_js: stable

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: build
  committer-from-gh: true
  verbose: true
  on:
    branch: publish

cache:
  directories:
<<<<<<< HEAD
    - node_modules
  
branches:
  only:
    - publish
=======
  - node_modules

script:
  - npm run build

branches:
  only:
    - master
>>>>>>> master
