import html from './index.html';

export default {
  title: 'cascadeOrganizationSelect',
  author: 'ryan.bian',
  type: 'directive',
  keyName: 'cascadeOrganizationSelectDirective',
  name: '组织&城市级联选择',
  date: '2018-04-3',
  description: '城市级联选择',
  scope: [
    {
      type: 'string',
      key: 'model',
      // exampleValue: '7bcb87d',
      exampleValue: ['huabeiqu','dongbeiqu','测试事业部'],
      description: 'model',
    },
    {
      type: 'string',
      key: 'mode',
      exampleValue: 'MULTIPLE',
      // exampleValue: 'SINGLE',
      description: '选择模式，SINGLE 或者 MULTIPLE,  默认单选 SINGLE',
    },
    {
      type: 'string',
      key: 'label',
      scopeType: '@',
      exampleValue: '城市',
      description: 'label',
    },
    {
      type: 'number',
      key: 'width',
      scopeType: '@',
      exampleValue: 160,
      description: '宽度',
    },
    {
      type: 'string',
      key: 'openCityType',
      scopeType: '@',
      exampleValue: 'GOODS_TAXI',
      description: '开城业务类型枚举 整车：GOODS_TAXI 零担：PART_LOAD 大客户：KA 班车：ARER_BUS',
    },
    {
      type: 'boolean',
      key: 'isActivated',
      exampleValue: true,
      description: '是否开城',
    },
    {
      type: 'boolean',
      key: 'cityOnly',
      scopeType: '=',
      exampleValue: false,
      description: '是否只能选择城市',
    },
    {
      type: 'boolean',
      key: 'readonly',
      scopeType: '=',
      // exampleValue: true,
      exampleValue: false,
      description: '只读模式',
    },
    {
      type: 'boolean',
      key: 'ignoreDataPermission',
      scopeType: '=',
      // exampleValue: true,
      exampleValue: false,
      description: '忽略数据权限切换，默认为 false',
    },
    {
      type: 'string',
      key: 'prependOptionType',
      scopeType: '@',
      exampleValue: 'CONCAT_ALL',
      // exampleValue: 'PARENT_VALUE',
      description: '前置选项值模式 可选 \'PARENT_VALUE\': 大区value 或 \'CONCAT\': 包含全部城市value，逗号分隔 或 \'CONCAT_ALL\'',
    },
    {
      type: 'string',
      key: 'apiUrl',
      scopeType: '@',
      exampleValue: '//green-sun-9840.getsandbox.com/selectCascadeRbacOrganizationByCode',
      description: '接口地址，默认不用传',
    },
    {
      type: 'function',
      key: 'sourceFormatter',
      description: '处理数据格式，返回对象必须包含 name 和 value 字段'
    }
  ],
  deps: [''],
  html,
  api: '',
  htmlUrl: '',
};